# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
#title:            Alex LaPrade
url:              http://lapra.de
shorturl:         lapra.de
paginate:         10
baseurl:          /
author:
  name:           'Alex LaPrade'
  url:            http://lapra.de
  email:          alex@lapra.de

# Custom vars
version:          1.0.0
github:
  repo: